apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b411fe039de55924

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs
spec:
  volumeName: expense-efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static 
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #docker run -v hostpath:containrpath
    - name: ebs-static
      mountPath: /usr/share/nginx/html   #continer
  volumes:
  - name: expense-efs         #from where does this volume come from
    persistentVolumeClaim:   #this volume comes fom PVC
      claimName: expense-efs

#what we are doing here is accessing EBS volumes in this path /usr/share/nginx/html  

---
#accessing pod using services
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007

