kind: Pod
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course #name of the env variable
        value: devops #value of the env variable
      - name: trainer
        value: "Deepak Gajula"
      - name: duration
        value: "120hr"

