kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
  